# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICKRfOaFstctO7Fn_BokqD8YDeoc-BA1
"""



import nest_asyncio
nest_asyncio.apply()

from openai import OpenAI
from telegram import Update, ReplyKeyboardMarkup
from telegram.ext import ApplicationBuilder, MessageHandler, CommandHandler, ContextTypes, filters

import os
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
OPENROUTER_KEY = os.environ.get("OPENROUTER_KEY")

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_KEY,
)

SYSTEM_PROMPT = """Ты — Анфиса, менеджер по продажам бренда Mari-Line.
Веди диалог как живой вежливый человек:
- На приветствие отвечай приветствием
- Не вываливай всю информацию сразу
- Отвечай коротко и только на то что спросили
- НИКОГДА не придумывай товары которых нет в списке ассортимента. Если товара нет — честно скажи что его нет.
- Не будь навязчивой

АССОРТИМЕНТ:
Платье Спорт Шик, арт. 2554
Цена: 2500 руб.
Размеры: 42-54
Состав: 95% хлопок, 5% эластан (футер двухнитка)
Цвет: Navy Blue (глубокий тёмно-синий)
Описание: А-силуэт, спущенное плечо, карман-арка сзади, длина миди."""

MENU = ReplyKeyboardMarkup(
    [["📦 Каталог", "📏 Таблица размеров"],
     ["🚚 Доставка", "💬 Задать вопрос"]],
    resize_keyboard=True
)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Привет! Я Анфиса, менеджер Mari-Line 👗\nЧем могу помочь?",
        reply_markup=MENU
    )

async def answer(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_text = update.message.text
    response = client.chat.completions.create(
        model="nvidia/nemotron-3-super-120b-a12b:free",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_text}
        ]
    )
    await update.message.reply_text(response.choices[0].message.content)

app = ApplicationBuilder().token(TELEGRAM_TOKEN).build()
app.add_handler(CommandHandler("start", start))
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, answer))
app.run_polling()
